name: fixmyclass
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shared_preferences: ^2.2.3
  firebase_messaging: ^15.2.7
  firebase_core: ^3.13.0
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.5
  carousel_slider: ^5.1.1
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  flutter_google_places_hoc081098: ^2.0.0
  google_maps_webservice_ex: ^0.0.1+3








dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
    - packages/flutter_google_places_hoc081098/assets/
